### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank:  128
lora_alpha: 256
overwrite_cache: true
### dataset
dataset: train
template: qwen2_vl
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
# preprocessing_num_workers: 16
# streaming: true

### output
output_dir: saves/Qwen2-VL-7B-Instruct/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
freeze_vision_tower: false

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 100
